// https://mui.com/material-ui/material-icons/
import {
	AccountCircleOutlined as AccountCircleIcon,
	AddRounded as AddIcon,
	DarkModeRounded as DarkIcon,
	LightModeRounded as LightIcon,
	CloseRounded as CloseIcon,
	LogoutRounded as LogoutIcon,
	PersonRounded as PersonIcon,
	SettingsRounded as SettingsIcon,
	ChevronLeftRounded as ArrowLeftIcon,
	ChevronRightRounded as ArrowRightIcon,
	DeleteOutlineRounded as DeleteIcon,
	EditRounded as EditIcon,
	MoreVertRounded as MoreIcon,
	MenuRounded as MenuIcon,
	TagRounded as TagIcon,
	LinkRounded as LinkIcon,
	StarBorderRounded as StarBorderIcon,
	StarRounded as StarIcon,
	ExpandMoreRounded as ExpandMoreIcon,
	FilterListRounded as FilterIcon,
	SearchRounded as SearchIcon,
	SaveRounded as SaveIcon,
	CheckCircleRounded as CheckCircleIcon,
	RadioButtonUncheckedOutlined as CircleIcon,
	CheckOutlined as CheckIcon,
	MailRounded as MailIcon,
	CakeRounded as BirthdayIcon,
	LoginRounded as LoginIcon,
	PersonAddRounded as SignUpIcon,
	UploadFileOutlined as UploadIcon
} from "@mui/icons-material";

const Icons = Object.freeze({
	ACCOUNT: PersonIcon,
	ACCOUNT_CIRCLE: AccountCircleIcon,
	ADD: AddIcon,
	ARROW_LEFT: ArrowLeftIcon,
	ARROW_RIGHT: ArrowRightIcon,
	BIRTHDAY: BirthdayIcon,
	CHECK: CheckIcon,
	CHECK_CIRCLE: CheckCircleIcon,
	CIRCLE: CircleIcon,
	CLOSE: CloseIcon,
	DARK: DarkIcon,
	DELETE: DeleteIcon,
	EDIT: EditIcon,
	EXPAND_MORE: ExpandMoreIcon,
	FILTER: FilterIcon,
	LIGHT: LightIcon,
	LINK: LinkIcon,
	LOGOUT: LogoutIcon,
	LOGIN: LoginIcon,
	MAIL: MailIcon,
	MENU: MenuIcon,
	MORE: MoreIcon,
	SAVE: SaveIcon,
	SEARCH: SearchIcon,
	SETTINGS: SettingsIcon,
	SIGN_UP: SignUpIcon,
	STAR: StarIcon,
	STAR_BORDER: StarBorderIcon,
	UPLOAD: UploadIcon,
	TAG: TagIcon
});

type IconType = typeof Icons[keyof typeof Icons];

export { Icons, IconType };
